//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kutuphaneEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kitap()
        {
            this.islem = new HashSet<islem>();
        }
    
        public int kitapno { get; set; }
        public string isbnno { get; set; }
        public string kitapadi { get; set; }
        public Nullable<int> yazarno { get; set; }
        public Nullable<int> turno { get; set; }
        public Nullable<int> sayfasayisi { get; set; }
        public Nullable<int> puan { get; set; }
    
        public virtual tur tur { get; set; }
        public virtual yazar yazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islem> islem { get; set; }
    }
}
